.gitignore, hub/.eslintrc, hub/package-lock.json, hub/package.json, hub/src/server/authentication.js, hub/src/server/driverModel.js, hub/src/server/drivers/DBXDriver.js, hub/src/server/http.js, hub/src/server/server.js
This pull request will allow users to use Dropbox as a storage.
In order to enable this driver edit your `config.json`:
```
"readURL": "<required>",
"driver": "dropbox",
...
"dropbox": {
"accessToken": "<access token>",
"storageRootDirectory": "<name of root directory (optional)>"
},
...
```
=> #121 Support driver models with read paths (e.g. Dropbox or Google Drive)

hub/README.md
possible fix for the following error while attempting to clone gaia with instructions from /hub/README.md
```
$ git clone git@github.com:blockstack/gaia.git
Cloning into 'gaia'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
=> git@github.com: Permission denied

hub/.eslintrc, hub/src/server/drivers/diskDriver.js, hub/src/server/http.js, hub/test/test.js
Fix the list-files implementation for the disk driver so it lists all files (like `find`), not just only the top-level directories.  This makes it consistent with the rest of the drivers on list-files.  Update the tests to test this new behavior.
=> Fix list-files for disk

hub/src/server/drivers/diskDriver.js
On `list-files`, have the disk driver return `{ entries: [], page: 1 }` (or whatever `page + 1` is) in the event that the directory being listed does not exist or the path is not a directory.  Before, this would throw an exception on the server.
=> Return an empty response if the directory or file does not exist

hub/CHANGELOG.md, hub/package.json, hub/src/server/authentication.js, hub/test/test.js
See issue #147 --
Simple patch to allow loose casing in the bearer prefix for authentication headers.
=> Hotfix for loose casing in bearer prefix

reader/src/http.js
Tagging @GInxh since this may be affecting work on the Gaia VMs.
=> Fix reader bug with storageRootDirectory config key used for file GETs.

hub/package.json, hub/src/server/drivers/diskDriver.js
When specifying an absolute path like `/tmp/gaia` the function that ensures the directory exists (mimicking `mkdir -p`) was failing on MacOS. Looks like it was doing an lstat on the path `/` and ending up trying to create a path like `//tmp/gaia`. This may have been working on linux - not sure.
Replaced the function with the popular `fs-extra` lib which includes a cross platform mkdirp/ensureDir.
=> Fix disk driver bug with the recursive-mkdir function.

hub/CHANGELOG.md, hub/package.json, hub/src/server/authentication.js, hub/src/server/server.js, hub/test/src/testHttp.js
This wraps the server handler functions in promise.resolve so that exceptions thrown in the handler are caught by the `http` object's `.catch` clauses.
This has the effect of correctly returning errors messages that used to return 500s.
Added a test case to the `testHttp` unit tests to deal with this.
=> Hotfix for promise rejection behavior

hub/package-lock.json, hub/package.json, hub/src/server/authentication.js, hub/test/src/testAuth.js, hub/test/src/testServer.js
This deprecates the annual timestamp in the challenge text -- it just replaces it with '0'.
This incorporates legacy years (2018, 2019) in challenge text checks as well.
=> Deprecate timestamps

.github/pull_request_template.md, CONTRIBUTING.md, LICENSE
This is a pretty skeletal CONTRIBUTING doc that roughly describes the PR review process, and what the PR author and PR reviewer are responsible for.
The goal here is to highlight what part of the review process affects QA specifically for Gaia.
The important things to check for QA in Gaia are:
1. Whether or not authentication tokens are affected by a particular PR.
2. Whether or not the PR changes how the deployed hub writes or expects to read data.
3. Whether or not the PR expects to add significant load to the hub server.
And so this was added to the explicit instructions for a reviewer.
=> PR Review Process and Submission Guidelines

hub/src/server/drivers/S3Driver.ts, hub/test/src/testDrivers.ts, hub/test/src/testDrivers/mockTestDrivers.ts
Provide better support for using cloud storage services that use S3 compatible APIs. 
Two notable changes:
* Allow the S3 driver `getReadURLPrefix()` endpoint to be configurable rather than hardcoded to `s3.amazonaws.com`, no longer requiring overriding through hub-level `readURL` config. 
* Use [`listObjects`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjects-property) instead of [`listObjectsV2`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectsV2-property) which has more consistent behavior for pagination across tested services (so far AWS, DigitalOcean Spaces, and Wasabi Hot Cloud Storage). 
Tested using all the cloud driver integration tests against [DigitalOcean Spaces](https://www.digitalocean.com/products/spaces/), [Wasabi Hot …
=> [S3 driver] Endpoint config for using services other than AWS

hub/etc/config.sample.s3.json, hub/src/server/revocations.ts
* Add `cache-control: no-cache` header to revocation fetch.
* Avoid reading revocation fetch contents if status code is bad (waste of hub resources pulling down any fancy CDN's error page content). 
No additional tests. I can implement tests later this week.
=> Add `no-cache` header to revocation fetch

admin/package.json, hub/package.json, reader/package.json
Update package.json `start` commands for more appropriate prod-usage in dockerfiles. 
Use `build && node index.js` rather than `ts-node index.ts` in `npm run start`. Since ts-node is not recommended for prod usage. 
Ran `npm run start` on all three sub-projects. 
(TODO: run docker)
n/a
=> Prod-ready package.json "start" commands

README.md
Removes the direct reference to Heroku one-click deploys from the readme, and instead directs to our documentation website.
=> Remove heroku one-click deploy

admin/package.json, hub/package.json, reader/package.json
Fix out-of-memory crash and/or super slow hub startup on low spec VM. 
Running `npm run start` for the hub on my low spec VM (1GB memory, 1 vCPU) is either taking a ton of time in the `eslint` script, or getting killed from out-of-memory. Example:
```
$ npm run start
> gaia-hub@2.5.0 start /home/matt/gaia/hub
> npm run build && node lib/index.js
> gaia-hub@2.5.0 build /home/matt/gaia/hub
> npm run lint && tsc && chmod +x lib/index.js
> gaia-hub@2.5.0 lint /home/matt/gaia/hub
> eslint --ext .ts ./src
Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! gaia-hub@2.5.0 lint: `eslint --ext .ts ./src`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the gaia-hub@2.5.0 lint script.
```
Note: eslint performs smarter checks w/ typescript integration, and so is much more resource …
=> Remove lint from the `build` / `start` commands. 

.eslintignore, hub/config-schema.json, hub/package-lock.json, hub/package.json, hub/src/server/ProofChecker.ts, hub/src/server/config.ts, hub/src/server/drivers/AzDriver.ts, hub/src/server/drivers/GcDriver.ts, hub/src/server/drivers/S3Driver.ts, hub/src/server/drivers/diskDriver.ts, hub/src/server/http.ts, hub/src/server/server.ts, hub/test/src/testConfig.ts, hub/test/src/testHttp.ts
Based off of discussion in similar previous PR https://github.com/blockstack/gaia/pull/204.
And issues https://github.com/blockstack/blockstack-browser/pull/1833#issuecomment-480088549 and https://github.com/blockstack/docs.blockstack/issues/198
Remove duplicate config typedefs, generate json schema file on build. 
This does not perform actual on-load schema enforcement that is done in https://github.com/blockstack/gaia/pull/204. 
Shouldn't be any logic changes to hub functionality. 
`npm run test`
No changes.
=> Config schema generation

README.md, hub/CHANGELOG.md, hub/package.json, hub/src/server/drivers/AzDriver.ts, hub/src/server/errors.ts, hub/src/server/http.ts, hub/test/src/testDrivers.ts, hub/test/src/testDrivers/InMemoryDriver.ts, hub/test/src/testHttp.ts
https://github.com/blockstack/gaia/issues/228
Fix 500 error during concurrent writes to same file for some drivers. 
Error `409 Conflict` is returned. 
Azure is the only service that errors during this situation. All others perform conflict resolution on their end, usually `last writer wins`. 
Implemented integration tests for concurrent writes, performed on all drivers. 
=> Return error 409 on concurrent writes error

hub/CHANGELOG.md, hub/package.json, hub/src/server/revocations.ts, hub/test/src/testServer.ts
Fix https://github.com/blockstack/gaia/issues/232
> We should set the `noDisposeOnSet` option in the LRUCache initialization (see: https://www.npmjs.com/package/lru-cache#options).
> 
> The way that we currently count evictions will be a large overestimate because of this.
Set flag. 
Added tests to reproduce bug and confirm fix. 
=> Set lrucache `noDisposeOnSet`

hub/config-schema.json, hub/config.sample.json, hub/etc/config.sample.disk.json, hub/etc/config.sample.gcloud.json, hub/etc/config.sample.s3.json, hub/package.json, hub/src/index.ts, hub/src/server/config.ts, hub/test/data/invalid-schema-def.json, hub/test/src/testConfig.ts
From https://github.com/blockstack/gaia/pull/204#pullrequestreview-223293778
> While recently setting up a personal gaia hub I ran into a couple hiccups that required briefly going through the config related code. I think Hank just ran into similar situation. I think config schema checking that showed console warnings would be useful for this
Loosely based off original PR https://github.com/blockstack/gaia/pull/204
Uses the most popular json schema validation lib [`ajv`](https://www.npmjs.com/package/ajv). 
Outputs warnings for:
* Missing config params - only a couple are required by the schema right now. 
* Params that are of the wrong type or out of range. 
* (Most useful feature) "Extra" params found in the config, which are almost always typos or similarly accidental incorrect usage. …
=> Schema validation warnings

README.md, hub/src/server/driverModel.ts, hub/src/server/drivers/AzDriver.ts, hub/src/server/drivers/GcDriver.ts, hub/src/server/drivers/S3Driver.ts, hub/src/server/drivers/diskDriver.ts, hub/test/src/testDrivers.ts, hub/test/src/testDrivers/InMemoryDriver.ts
https://github.com/blockstack/gaia/issues/220, https://github.com/blockstack/gaia/issues/240
Implement read file support in all drivers. Will be used for the incrementing index file version keys as part of the collections historical naming scheme. 
`performRead` returns same information as `performStat` but with an added NodeJS `stream.Readable` data field. Extra precaution taken to avoid buffering an entire file stream in memory -- allows the future invocations to perform streaming operations with appropriate back-pressure handling. For example, using a streaming json util that could find and increment a key-val pair on a theoretical larger-than-memory index.json file. 
`DRIVER_CONFIG_TEST_DATA=configs/drivers.json npm test`
Full integration testing implement for all supported drivers. …
=> ReadFile driver operation primitive

README.md, admin/.eslintrc.js, hub/.eslintrc.js, hub/src/server/drivers/GcDriver.ts, hub/src/server/drivers/diskDriver.ts, hub/src/server/http.ts, hub/src/server/utils.ts, hub/test/src/testDrivers/InMemoryDriver.ts, hub/test/src/testHttp.ts, reader/.eslintrc.js
Implement mutex around file http handlers that perform file mutations: `POST /store/address/file` and `DELETE /delete/address/file`.
A mutex is unique to a `address/file` endpoint. When an operation is in progress for a given resource, subsequence requests to the modify the resource are immediately rejected with an HTTP 409 Conflict. 
Instantiating many concurrent POST or DELETE requests to the same endpoint, using something like curl or a load tester. 
Tests implemented for full coverage of the mutex implementation and http conflict error paths. 
=> Implement mutex around file mutation http handlers

hub/CHANGELOG.md, hub/src/server/http.ts, hub/test/src/testHttp.ts
https://github.com/blockstack/gaia/issues/254
Set the [Access-Control-Max-Age](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age) CORs header. This prevents browsers from making redundant round-trip OPTION requests for every POST to gaia. 
Set the CORs `Access-Control-Max-Age` header to 24 hours. 
\- 
CORs option response header test implemented. 
=> Set the CORs preflight header to be cached for 24 hours

hub/src/server/http.ts, hub/test/src/testHttp.ts
Fix https://github.com/blockstack/gaia/issues/266
https://github.com/blockstack/gaia/blob/ef0771833cd56200e08e18631e62467f24e086af/hub/src/server/http.ts#L125
Minor bug with the delete file handler. Its `BadPathError` error returns a 400 and the others return a 403
=> Fix #266 - incorrect http error code on delete file BadPathError

hub/CHANGELOG.md, hub/config-schema.json, hub/src/server/config.ts
Closes https://github.com/blockstack/gaia/issues/273
Update the default `cacheControl` config setting to match the PBC hub.
For context see https://github.com/blockstack/blockstack.js/issues/732#issuecomment-544659629
Describe how that goal was achieved through the submitted implementation.
Setting performed and documented at https://github.com/blockstack/blockstack.js/issues/732#issuecomment-544659629
=> Change default `cache-control` setting

.vscode/launch.json, hub/package.json, hub/src/server/drivers/GcDriver.ts, hub/test/src/testDrivers.ts, hub/test/src/testDrivers/InMemoryDriver.ts, hub/test/src/testDrivers/integrationTestDrivers.ts, reader/src/http.ts, reader/src/server.ts, reader/test/test.ts
* Implement http HEAD request support in `reader` -- required for future efficient etag lookups in blockstack.js.
* Fix DDoS vulnerability in `reader` by refactoring blocking/syncronous file system operations.
* Implement unit tests for ensuring correct read-endpoint HTTP headers for all drivers.
* Use storage credentials file for integration testing if available when running npm test script.
Integration tests against all supported drivers. 
- (will PR into develop once the etag/MVCC PR is merged into develop)
- (need to update the CHANGELOG)
=> Reader http HEAD support

.vscode/launch.json, README.md, hub/CHANGELOG.md, hub/README.md, hub/package.json, hub/src/server/driverModel.ts, hub/src/server/drivers/AzDriver.ts, hub/src/server/drivers/GcDriver.ts, hub/src/server/drivers/S3Driver.ts, hub/src/server/drivers/diskDriver.ts, hub/src/server/errors.ts, hub/src/server/http.ts, hub/src/server/server.ts, hub/test/src/testDrivers.ts, hub/test/src/testDrivers/InMemoryDriver.ts, hub/test/src/testDrivers/integrationTestDrivers.ts, hub/test/src/testDrivers/mockTestDrivers.ts, hub/test/src/testHttp.ts, hub/test/src/testServer.ts, reader/src/http.ts, reader/src/server.ts, reader/test/test.ts
This is the Gaia portion of the optimistic concurrency control changes I've been working on, referenced in this issue: blockstack/gaia#267
With this change, Gaia makes use of an optional etag (entity tag), included in the `if-match` request header, to validate that a file hasn't been changed externally since the client attempting to `write` to it last `read` it. Additionally, Gaia will now return a fresh `etag` in the response object returned on `write` operations.
This change helps prevent accidental overwrites and data loss, encouraging developers to create UIs to let users deal with these conflicts.
I've been testing this manually with a [custom Gaia hub](http://gaia.reedrosenbluth.com) running this code on digital ocean. I've been using a [small demo …
=> Concurrency control

.circleci/config.yml, admin/Dockerfile, admin/package-lock.json, admin/package.json, hub/CHANGELOG.md, hub/Dockerfile, hub/package-lock.json, hub/package.json, hub/src/server/driverModel.ts, hub/src/server/drivers/AzDriver.ts, hub/src/server/drivers/GcDriver.ts, hub/src/server/drivers/S3Driver.ts, hub/src/server/drivers/diskDriver.ts, hub/src/server/utils.ts, hub/test/src/testDrivers.ts, hub/test/src/testDrivers/InMemoryDriver.ts, hub/test/src/testDrivers/integrationTestDrivers.ts, package-lock.json, package.json, reader/Dockerfile, reader/package-lock.json, reader/package.json
Fix https://github.com/blockstack/gaia/issues/292
Fix https://github.com/blockstack/gaia/issues/293
Fix regression where Azure driver was throwing a 5xx server error when a `content-length: 0` header file POST was made. 
Added integration tests for these cases -- found and fixed a bug with S3 driver returning undefined content-length in the same scenario. 
Misc package upgrades. 
=> Fix 500 error for empty file uploads with Azure driver

hub/CHANGELOG.md, hub/package.json, hub/src/server/drivers/AzDriver.ts, hub/test/src/testDrivers.ts, hub/test/src/testHttp.ts
This PR fixes a bug in which a 500 error was getting thrown instead of a 412 when write request was made with the if-none-match header set, and the file attempting to be written already exists.
#306
Added an integration test.
=> fix: throw PreconditionFailedError if if-none-match is set and file exists

deploy/README.md
On the instructions to setup a gaia hub on a MAC with docker-compose, the folder was incorrect.
=> Update instructions to setup a GAIA hub

admin/README.md
Updated steps to launch Gaia Admin Service
=> Update steps to launch Gaia Admin Service

deploy/cloudformation.yaml
Updated the cloudformation template to avoid and SSH access problem [reported on the forum](https://forum.stacks.org/t/cors-issue-accessing-my-own-gaia-with-aws-cloud/13141)
=> GAIA Cloudformation SSH access fix

deploy/docker/gaiahub.sh
* Fixes issue #400
* Better error handling on `gaiahub.sh`
=> Improves error handling on script gaiahub.sh
